name: build-image
run-name: Building docker image.
on:
  push:
    tags:
      - 'v**'
jobs:
  build-arm64:
    environment: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.arm64
          platforms: linux/arm64
          push: true
          tags: linusus/utsma:zed-gst-ros2-${{ github.ref_name }}
